// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

interface MockAuthClient {
  signInWithOAuth?: (args: {
    provider: string;
    options?: { redirectTo?: string };
  }) => Promise<{ error: unknown }>;
}

export const lovable = {
  auth: {
    signInWithOAuth: async (
      provider: "google" | "apple" | "microsoft" | "lovable",
      opts?: SignInOptions,
    ) => {
      // If we are using the Firebase-backed mock client, bypass Lovable's OAuth and call the mock directly.
      const SUPABASE_URL =
        import.meta.env.VITE_SUPABASE_URL ||
        (typeof process !== "undefined" && process.env?.SUPABASE_URL);
      if (!SUPABASE_URL) {
        const mockAuth = supabase.auth as MockAuthClient;
        if (typeof mockAuth.signInWithOAuth === "function") {
          const { error } = await mockAuth.signInWithOAuth({
            provider,
            options: {
              redirectTo: opts?.redirect_uri || window.location.origin,
            },
          });
          if (error) {
            return { error: error instanceof Error ? error : new Error(String(error)) };
          }
          return { redirected: false, error: null };
        }
      }

      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      try {
        await supabase.auth.setSession(result.tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
