/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedSetupFirstAdminRouteImport } from './routes/_authenticated/setup.first-admin'
import { Route as AuthenticatedReviewAttemptIdRouteImport } from './routes/_authenticated/review.$attemptId'
import { Route as AuthenticatedResultsAttemptIdRouteImport } from './routes/_authenticated/results.$attemptId'
import { Route as AuthenticatedExamAttemptIdRouteImport } from './routes/_authenticated/exam.$attemptId'
import { Route as AuthenticatedAdminResultsRouteImport } from './routes/_authenticated/admin.results'
import { Route as AuthenticatedAdminExamsRouteImport } from './routes/_authenticated/admin.exams'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminExamsIndexRouteImport } from './routes/_authenticated/admin.exams.index'
import { Route as AuthenticatedExamStartExamIdRouteImport } from './routes/_authenticated/exam.start.$examId'
import { Route as AuthenticatedAdminResultsAttemptIdRouteImport } from './routes/_authenticated/admin.results.$attemptId'
import { Route as AuthenticatedAdminExamsExamIdRouteImport } from './routes/_authenticated/admin.exams.$examId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSetupFirstAdminRoute =
  AuthenticatedSetupFirstAdminRouteImport.update({
    id: '/setup/first-admin',
    path: '/setup/first-admin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReviewAttemptIdRoute =
  AuthenticatedReviewAttemptIdRouteImport.update({
    id: '/review/$attemptId',
    path: '/review/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResultsAttemptIdRoute =
  AuthenticatedResultsAttemptIdRouteImport.update({
    id: '/results/$attemptId',
    path: '/results/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExamAttemptIdRoute =
  AuthenticatedExamAttemptIdRouteImport.update({
    id: '/exam/$attemptId',
    path: '/exam/$attemptId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminResultsRoute =
  AuthenticatedAdminResultsRouteImport.update({
    id: '/results',
    path: '/results',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminExamsRoute = AuthenticatedAdminExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminExamsIndexRoute =
  AuthenticatedAdminExamsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminExamsRoute,
  } as any)
const AuthenticatedExamStartExamIdRoute =
  AuthenticatedExamStartExamIdRouteImport.update({
    id: '/exam/start/$examId',
    path: '/exam/start/$examId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminResultsAttemptIdRoute =
  AuthenticatedAdminResultsAttemptIdRouteImport.update({
    id: '/$attemptId',
    path: '/$attemptId',
    getParentRoute: () => AuthenticatedAdminResultsRoute,
  } as any)
const AuthenticatedAdminExamsExamIdRoute =
  AuthenticatedAdminExamsExamIdRouteImport.update({
    id: '/$examId',
    path: '/$examId',
    getParentRoute: () => AuthenticatedAdminExamsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/exams': typeof AuthenticatedAdminExamsRouteWithChildren
  '/admin/results': typeof AuthenticatedAdminResultsRouteWithChildren
  '/exam/$attemptId': typeof AuthenticatedExamAttemptIdRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/review/$attemptId': typeof AuthenticatedReviewAttemptIdRoute
  '/setup/first-admin': typeof AuthenticatedSetupFirstAdminRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/exams/$examId': typeof AuthenticatedAdminExamsExamIdRoute
  '/admin/results/$attemptId': typeof AuthenticatedAdminResultsAttemptIdRoute
  '/exam/start/$examId': typeof AuthenticatedExamStartExamIdRoute
  '/admin/exams/': typeof AuthenticatedAdminExamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/results': typeof AuthenticatedAdminResultsRouteWithChildren
  '/exam/$attemptId': typeof AuthenticatedExamAttemptIdRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/review/$attemptId': typeof AuthenticatedReviewAttemptIdRoute
  '/setup/first-admin': typeof AuthenticatedSetupFirstAdminRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/exams/$examId': typeof AuthenticatedAdminExamsExamIdRoute
  '/admin/results/$attemptId': typeof AuthenticatedAdminResultsAttemptIdRoute
  '/exam/start/$examId': typeof AuthenticatedExamStartExamIdRoute
  '/admin/exams': typeof AuthenticatedAdminExamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/exams': typeof AuthenticatedAdminExamsRouteWithChildren
  '/_authenticated/admin/results': typeof AuthenticatedAdminResultsRouteWithChildren
  '/_authenticated/exam/$attemptId': typeof AuthenticatedExamAttemptIdRoute
  '/_authenticated/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/_authenticated/review/$attemptId': typeof AuthenticatedReviewAttemptIdRoute
  '/_authenticated/setup/first-admin': typeof AuthenticatedSetupFirstAdminRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/exams/$examId': typeof AuthenticatedAdminExamsExamIdRoute
  '/_authenticated/admin/results/$attemptId': typeof AuthenticatedAdminResultsAttemptIdRoute
  '/_authenticated/exam/start/$examId': typeof AuthenticatedExamStartExamIdRoute
  '/_authenticated/admin/exams/': typeof AuthenticatedAdminExamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/dashboard'
    | '/admin/audit'
    | '/admin/exams'
    | '/admin/results'
    | '/exam/$attemptId'
    | '/results/$attemptId'
    | '/review/$attemptId'
    | '/setup/first-admin'
    | '/admin/'
    | '/admin/exams/$examId'
    | '/admin/results/$attemptId'
    | '/exam/start/$examId'
    | '/admin/exams/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/admin/audit'
    | '/admin/results'
    | '/exam/$attemptId'
    | '/results/$attemptId'
    | '/review/$attemptId'
    | '/setup/first-admin'
    | '/admin'
    | '/admin/exams/$examId'
    | '/admin/results/$attemptId'
    | '/exam/start/$examId'
    | '/admin/exams'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/exams'
    | '/_authenticated/admin/results'
    | '/_authenticated/exam/$attemptId'
    | '/_authenticated/results/$attemptId'
    | '/_authenticated/review/$attemptId'
    | '/_authenticated/setup/first-admin'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/exams/$examId'
    | '/_authenticated/admin/results/$attemptId'
    | '/_authenticated/exam/start/$examId'
    | '/_authenticated/admin/exams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/setup/first-admin': {
      id: '/_authenticated/setup/first-admin'
      path: '/setup/first-admin'
      fullPath: '/setup/first-admin'
      preLoaderRoute: typeof AuthenticatedSetupFirstAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review/$attemptId': {
      id: '/_authenticated/review/$attemptId'
      path: '/review/$attemptId'
      fullPath: '/review/$attemptId'
      preLoaderRoute: typeof AuthenticatedReviewAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results/$attemptId': {
      id: '/_authenticated/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/results/$attemptId'
      preLoaderRoute: typeof AuthenticatedResultsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exam/$attemptId': {
      id: '/_authenticated/exam/$attemptId'
      path: '/exam/$attemptId'
      fullPath: '/exam/$attemptId'
      preLoaderRoute: typeof AuthenticatedExamAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/results': {
      id: '/_authenticated/admin/results'
      path: '/results'
      fullPath: '/admin/results'
      preLoaderRoute: typeof AuthenticatedAdminResultsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/exams': {
      id: '/_authenticated/admin/exams'
      path: '/exams'
      fullPath: '/admin/exams'
      preLoaderRoute: typeof AuthenticatedAdminExamsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/exams/': {
      id: '/_authenticated/admin/exams/'
      path: '/'
      fullPath: '/admin/exams/'
      preLoaderRoute: typeof AuthenticatedAdminExamsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminExamsRoute
    }
    '/_authenticated/exam/start/$examId': {
      id: '/_authenticated/exam/start/$examId'
      path: '/exam/start/$examId'
      fullPath: '/exam/start/$examId'
      preLoaderRoute: typeof AuthenticatedExamStartExamIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/results/$attemptId': {
      id: '/_authenticated/admin/results/$attemptId'
      path: '/$attemptId'
      fullPath: '/admin/results/$attemptId'
      preLoaderRoute: typeof AuthenticatedAdminResultsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedAdminResultsRoute
    }
    '/_authenticated/admin/exams/$examId': {
      id: '/_authenticated/admin/exams/$examId'
      path: '/$examId'
      fullPath: '/admin/exams/$examId'
      preLoaderRoute: typeof AuthenticatedAdminExamsExamIdRouteImport
      parentRoute: typeof AuthenticatedAdminExamsRoute
    }
  }
}

interface AuthenticatedAdminExamsRouteChildren {
  AuthenticatedAdminExamsExamIdRoute: typeof AuthenticatedAdminExamsExamIdRoute
  AuthenticatedAdminExamsIndexRoute: typeof AuthenticatedAdminExamsIndexRoute
}

const AuthenticatedAdminExamsRouteChildren: AuthenticatedAdminExamsRouteChildren =
  {
    AuthenticatedAdminExamsExamIdRoute: AuthenticatedAdminExamsExamIdRoute,
    AuthenticatedAdminExamsIndexRoute: AuthenticatedAdminExamsIndexRoute,
  }

const AuthenticatedAdminExamsRouteWithChildren =
  AuthenticatedAdminExamsRoute._addFileChildren(
    AuthenticatedAdminExamsRouteChildren,
  )

interface AuthenticatedAdminResultsRouteChildren {
  AuthenticatedAdminResultsAttemptIdRoute: typeof AuthenticatedAdminResultsAttemptIdRoute
}

const AuthenticatedAdminResultsRouteChildren: AuthenticatedAdminResultsRouteChildren =
  {
    AuthenticatedAdminResultsAttemptIdRoute:
      AuthenticatedAdminResultsAttemptIdRoute,
  }

const AuthenticatedAdminResultsRouteWithChildren =
  AuthenticatedAdminResultsRoute._addFileChildren(
    AuthenticatedAdminResultsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminExamsRoute: typeof AuthenticatedAdminExamsRouteWithChildren
  AuthenticatedAdminResultsRoute: typeof AuthenticatedAdminResultsRouteWithChildren
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminExamsRoute: AuthenticatedAdminExamsRouteWithChildren,
  AuthenticatedAdminResultsRoute: AuthenticatedAdminResultsRouteWithChildren,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExamAttemptIdRoute: typeof AuthenticatedExamAttemptIdRoute
  AuthenticatedResultsAttemptIdRoute: typeof AuthenticatedResultsAttemptIdRoute
  AuthenticatedReviewAttemptIdRoute: typeof AuthenticatedReviewAttemptIdRoute
  AuthenticatedSetupFirstAdminRoute: typeof AuthenticatedSetupFirstAdminRoute
  AuthenticatedExamStartExamIdRoute: typeof AuthenticatedExamStartExamIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExamAttemptIdRoute: AuthenticatedExamAttemptIdRoute,
  AuthenticatedResultsAttemptIdRoute: AuthenticatedResultsAttemptIdRoute,
  AuthenticatedReviewAttemptIdRoute: AuthenticatedReviewAttemptIdRoute,
  AuthenticatedSetupFirstAdminRoute: AuthenticatedSetupFirstAdminRoute,
  AuthenticatedExamStartExamIdRoute: AuthenticatedExamStartExamIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
